server:
  port: 8011
spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  mail:
    host: smtp.mailtrap.io
    port: 2525
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/sbs_proj_2023?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: sbsst
    password: sbs123414
mybatis:
  type-aliases-package: com.khj.exam.demo.vo
  
custom:
  genFileDirPath: C:\work\sts-4.18.0.RELEASE-workspace
  siteName: SBS
  siteMainUri: http://localhost:8011
  emailFrom: no-reply@localhost
  emailFromName: SBS IT
  logging:
    dir: log
    level: debug